PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 1234,
  "title": "My First Post",
  "postType": "post",
  "slug": "my-first-post",
  "status": "draft",
  "content": "This is the content of my first post.",
  "schema": "{\"key\": \"value\"}",
  "featuredImageUrl": "http://example.com/image.jpg",
  "publishOn": "2024-08-01T00:00:00Z",
  "tags": ["tag1", "tag2", "tag3"],
  "metaOptions": [
    {
      "key": "author",
      "value": "Or Hasson"
    }
  ]
}