POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First Post",
    "postType": "post",
    "slug": "my-first-post",
    "status": "draft",
    "content": "This is the content of my first post.",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\":\"Person\"\r\n}",
    "featuredImageUrl": "http://example.com/image.jpg",
    "publishOn": "2024-08-01T00:00:00Z",
    "metaOptions": {
        "metaValue": "{\"sidebarEnabled\":true, \"footerActive\": true}"
    }
}